#!/bin/bash
#####################################
#                                   #
#  Encryptron: The Discreet Enigma  #
#                                   #
#####################################
#
# Ver: 1.0.0-a.1
# Author: npvq
# 2021-08-23
#
# Shell script that sets up environment to run Python.

# https://stackoverflow.com/a/246128/14387133
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

# echo "$DIR" # Debug

# Allows importing local modules.
if [ -z ${PYTHONPATH+x} ]; then
    export PYTHONPATH="$DIR"
else
    export PYTHONPATH="${PYTHONPATH}:${DIR}"
fi
# echo "$PYTHONPATH"

# Run the python script (For troubleshooting Terminal)
# if [ "$1" == "terminal" ]; then
#     /usr/bin/env python3 -i "$DIR/encryptron/terminal.py" "${@:2}" &
#     export ENCTERM_ID="$! "
#     alias resume='fg ${ENCTERM_ID}'
#     fg "$ENCTERM_ID"
#     # bruh
# else
/usr/bin/env python3 "$DIR/main.py" "$@"
# fi
